site_name: My Project Documentation
site_url: https://example.com
repo_url: https://github.com/jbalestrine/masterchief
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide/
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
