"""Monitor phase generators"""

from typing import Tuple
from echo.devops_suite.master_suite import BaseGenerator, ScriptType


class MonitorGenerator(BaseGenerator):
    """Generate monitor phase scripts"""
    
    def generate(self, task_type: str, **kwargs) -> Tuple[str, ScriptType]:
        """Generate a monitor script"""
        
        generators = {
            "metrics": self._metrics,
            "logging": self._logging,
            "tracing": self._tracing,
            "alerting": self._alerting,
            "dashboards": self._dashboards,
            "slo_sli": self._slo_sli,
            "uptime": self._uptime,
        }
        
        generator_func = generators.get(task_type, self._default)
        return generator_func(**kwargs)
    
    def _metrics(self, **kwargs) -> Tuple[str, ScriptType]:
        """Generate metrics collection configuration"""
        script = '''# Prometheus Metrics Configuration
# Generated by Echo 🌙

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'application'
    static_configs:
      - targets: ['localhost:8000']
    
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\\d+)?;(\\d+)
        replacement: $1:$2
        target_label: __address__

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

# Generated by Echo DevOps Master Suite 🌙
'''
        return script, ScriptType.YAML
    
    def _logging(self, **kwargs) -> Tuple[str, ScriptType]:
        """Generate logging configuration"""
        script = '''# Fluent Bit Logging Configuration
# Generated by Echo 🌙

[SERVICE]
    Flush        5
    Daemon       off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/log/containers/*.log
    Parser            docker
    Tag               kube.*
    Refresh_Interval  5
    Mem_Buf_Limit     5MB

[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token

[OUTPUT]
    Name  es
    Match *
    Host  elasticsearch
    Port  9200
    Index fluent-bit
    Type  _doc

[OUTPUT]
    Name   loki
    Match  *
    Host   loki
    Port   3100
    Labels job=fluentbit

# Generated by Echo DevOps Master Suite 🌙
'''
        return script, ScriptType.YAML
    
    def _tracing(self, **kwargs) -> Tuple[str, ScriptType]:
        """Generate distributed tracing configuration"""
        script = '''# Jaeger Tracing Configuration
# Generated by Echo 🌙

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 9411
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: ClusterIP
  ports:
  - port: 16686
    targetPort: 16686
    name: ui
  - port: 14268
    targetPort: 14268
    name: collector
  selector:
    app: jaeger

# Generated by Echo DevOps Master Suite 🌙
'''
        return script, ScriptType.YAML
    
    def _alerting(self, **kwargs) -> Tuple[str, ScriptType]:
        """Generate alerting rules"""
        script = '''# Prometheus Alerting Rules
# Generated by Echo 🌙

groups:
  - name: application_alerts
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors/sec for {{ $labels.instance }}"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is {{ $value }}s for {{ $labels.instance }}"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.instance }} of {{ $labels.job }} is down"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }}"

# Generated by Echo DevOps Master Suite 🌙
'''
        return script, ScriptType.YAML
    
    def _dashboards(self, **kwargs) -> Tuple[str, ScriptType]:
        """Generate Grafana dashboard"""
        script = '''{
  "dashboard": {
    "title": "Application Monitoring Dashboard",
    "tags": ["application", "monitoring"],
    "timezone": "browser",
    "panels": [
      {
        "id": 1,
        "title": "Request Rate",
        "type": "graph",
        "targets": [
          {
            "expr": "rate(http_requests_total[5m])",
            "legendFormat": "{{method}} {{path}}"
          }
        ]
      },
      {
        "id": 2,
        "title": "Error Rate",
        "type": "graph",
        "targets": [
          {
            "expr": "rate(http_requests_total{status=~\\"5..\\"}[5m])",
            "legendFormat": "{{status}} {{path}}"
          }
        ]
      },
      {
        "id": 3,
        "title": "Response Time (p95)",
        "type": "graph",
        "targets": [
          {
            "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
            "legendFormat": "95th percentile"
          }
        ]
      },
      {
        "id": 4,
        "title": "Active Connections",
        "type": "stat",
        "targets": [
          {
            "expr": "sum(rate(http_requests_total[1m]))",
            "legendFormat": "Requests/sec"
          }
        ]
      },
      {
        "id": 5,
        "title": "CPU Usage",
        "type": "graph",
        "targets": [
          {
            "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\\"idle\\"}[5m])) * 100)",
            "legendFormat": "{{instance}}"
          }
        ]
      },
      {
        "id": 6,
        "title": "Memory Usage",
        "type": "graph",
        "targets": [
          {
            "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
            "legendFormat": "{{instance}}"
          }
        ]
      }
    ],
    "refresh": "10s",
    "time": {
      "from": "now-1h",
      "to": "now"
    }
  }
}
'''
        return script, ScriptType.YAML
    
    def _slo_sli(self, **kwargs) -> Tuple[str, ScriptType]:
        """Generate SLO/SLI tracking configuration"""
        script = '''# Service Level Objectives (SLO) Configuration
# Generated by Echo 🌙

slos:
  - name: api_availability
    description: "API should be available 99.9% of the time"
    objective: 99.9
    sli:
      metric: up
      success_condition: "== 1"
    window: 30d
    error_budget: 0.1

  - name: api_latency
    description: "95% of requests should complete within 500ms"
    objective: 95
    sli:
      metric: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
      success_condition: "< 0.5"
    window: 30d

  - name: error_rate
    description: "Error rate should be below 1%"
    objective: 99
    sli:
      metric: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100
      success_condition: "< 1"
    window: 30d
    error_budget: 1

# Error Budget Burn Rate Alerts
alerts:
  - name: ErrorBudgetBurnRateHigh
    condition: "(1 - slo_availability) > (error_budget * 0.8)"
    severity: warning
    message: "Consuming error budget too quickly"

  - name: ErrorBudgetExhausted
    condition: "(1 - slo_availability) >= error_budget"
    severity: critical
    message: "Error budget exhausted"

# Generated by Echo DevOps Master Suite 🌙
'''
        return script, ScriptType.YAML
    
    def _uptime(self, **kwargs) -> Tuple[str, ScriptType]:
        """Generate uptime monitoring script"""
        script = '''#!/usr/bin/env bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════
# Uptime Monitoring Script
# Generated by Echo for Marsh 🌙
# ══════════════════════════════════════════════════════════════

URLS=(
    "https://example.com"
    "https://api.example.com/health"
)
CHECK_INTERVAL=60  # seconds
ALERT_WEBHOOK="${ALERT_WEBHOOK:-}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

alert() {
    local message="$1"
    log "ALERT: $message"
    
    if [ -n "$ALERT_WEBHOOK" ]; then
        curl -X POST "$ALERT_WEBHOOK" \
            -H 'Content-Type: application/json' \
            -d "{\\"text\\":\\"$message\\"}"
    fi
}

check_url() {
    local url="$1"
    local status=$(curl -s -o /dev/null -w "%{http_code}" -m 10 "$url" || echo "000")
    
    if [ "$status" = "200" ]; then
        log "✓ $url is UP (HTTP $status)"
        return 0
    else
        alert "✗ $url is DOWN (HTTP $status)"
        return 1
    fi
}

log "Starting uptime monitoring..."

while true; do
    for url in "${URLS[@]}"; do
        check_url "$url"
    done
    
    sleep "$CHECK_INTERVAL"
done
'''
        return script, ScriptType.BASH
    
    def _default(self, **kwargs) -> Tuple[str, ScriptType]:
        """Default monitor script"""
        script = '''#!/usr/bin/env bash
# Default monitor script
# Generated by Echo 🌙

echo "Monitor task - customize this script for your needs"
'''
        return script, ScriptType.BASH


__all__ = ["MonitorGenerator"]
