version: '3.7'
services:
  inspircd:
    image: inspircd/inspircd-docker:latest
    container_name: inspircd_dev
    restart: unless-stopped
    ports:
      - "6668:6667" # host 6668 -> container 6667 (6667 may be reserved on host)
      - "6697:6697"
    volumes:
      - ./inspircd-overrides/modules:/inspircd/modules:rw
    environment:
      - INSPIRCD_HOST=0.0.0.0
