"""Plan phase generators"""

from typing import Tuple
from echo.devops_suite.master_suite import BaseGenerator, ScriptType


class PlanGenerator(BaseGenerator):
    """Generate planning phase scripts"""
    
    def generate(self, task_type: str, **kwargs) -> Tuple[str, ScriptType]:
        """Generate a planning script"""
        
        generators = {
            "project_init": self._project_init,
            "sprint_planning": self._sprint_planning,
            "roadmap": self._roadmap,
            "capacity": self._capacity_planning,
            "risk_assessment": self._risk_assessment,
        }
        
        generator_func = generators.get(task_type, self._default)
        return generator_func(**kwargs)
    
    def _project_init(self, project_name: str = "myproject", **kwargs) -> Tuple[str, ScriptType]:
        """Generate project initialization script"""
        script = f'''#!/usr/bin/env bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════
# Project Initialization Script
# Generated by Echo for Marsh 🌙
# ══════════════════════════════════════════════════════════════

PROJECT_NAME="{project_name}"

log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}}

log "Initializing project: $PROJECT_NAME"

# Create project structure
mkdir -p "$PROJECT_NAME"/{{src,tests,docs,config}}

# Initialize Git
cd "$PROJECT_NAME"
git init
git config core.autocrlf false

# Create basic files
cat > README.md << 'EOF'
# $PROJECT_NAME

Project initialized by Echo DevOps Master Suite

## Getting Started

TODO: Add project description

EOF

cat > .gitignore << 'EOF'
__pycache__/
*.py[cod]
*$py.class
.venv/
venv/
*.log
.DS_Store
EOF

# Initialize Python project
cat > setup.py << 'EOF'
from setuptools import setup, find_packages

setup(
    name="${{PROJECT_NAME}}",
    version="0.1.0",
    packages=find_packages(),
    python_requires=">=3.10",
)
EOF

cat > requirements.txt << 'EOF'
# Add your dependencies here
EOF

log "Project $PROJECT_NAME initialized successfully! 🌙"
log "Next steps:"
log "  cd $PROJECT_NAME"
log "  git add ."
log "  git commit -m 'Initial commit'"
'''
        return script, ScriptType.BASH
    
    def _sprint_planning(self, sprint_number: int = 1, duration_weeks: int = 2, **kwargs) -> Tuple[str, ScriptType]:
        """Generate sprint planning template"""
        script = f'''# Sprint Planning - Sprint {sprint_number}
# Generated by Echo 🌙

## Sprint Information
- **Sprint Number**: {sprint_number}
- **Duration**: {duration_weeks} weeks
- **Start Date**: {{{{START_DATE}}}}
- **End Date**: {{{{END_DATE}}}}

## Sprint Goal
{{{{SPRINT_GOAL}}}}

## Team Capacity
- **Available Person-Days**: {{{{CAPACITY}}}}
- **Team Members**: {{{{TEAM_MEMBERS}}}}

## Sprint Backlog
| Story ID | Title | Story Points | Assignee | Status |
|----------|-------|--------------|----------|--------|
| {{{{STORY_ID}}}} | {{{{TITLE}}}} | {{{{POINTS}}}} | {{{{ASSIGNEE}}}} | To Do |

## Definition of Done
- [ ] Code complete
- [ ] Tests passing
- [ ] Code reviewed
- [ ] Documentation updated
- [ ] Deployed to staging
- [ ] Acceptance criteria met

## Risks and Dependencies
- {{{{RISKS}}}}

## Notes
{{{{NOTES}}}}

---
*Generated by Echo DevOps Master Suite*
'''
        return script, ScriptType.YAML
    
    def _roadmap(self, quarters: int = 4, **kwargs) -> Tuple[str, ScriptType]:
        """Generate product roadmap template"""
        script = f'''# Product Roadmap
# Generated by Echo 🌙

## Vision
{{{{PRODUCT_VISION}}}}

## Strategic Objectives
1. {{{{OBJECTIVE_1}}}}
2. {{{{OBJECTIVE_2}}}}
3. {{{{OBJECTIVE_3}}}}

'''
        for q in range(1, quarters + 1):
            script += f'''
## Q{q} - {{{{YEAR}}}}
### Themes
- {{{{THEME_1}}}}
- {{{{THEME_2}}}}

### Key Initiatives
| Initiative | Owner | Status | Timeline |
|------------|-------|--------|----------|
| {{{{INIT_NAME}}}} | {{{{OWNER}}}} | {{{{STATUS}}}} | {{{{TIMELINE}}}} |

'''
        
        script += '''
## Metrics and KPIs
- {{{{METRIC_1}}}}
- {{{{METRIC_2}}}}

---
*Generated by Echo DevOps Master Suite*
'''
        return script, ScriptType.YAML
    
    def _capacity_planning(self, team_size: int = 5, **kwargs) -> Tuple[str, ScriptType]:
        """Generate capacity planning script"""
        script = f'''#!/usr/bin/env python3
"""
Capacity Planning Calculator
Generated by Echo 🌙
"""

import datetime

# Configuration
TEAM_SIZE = {team_size}
WORKING_DAYS_PER_WEEK = 5
HOURS_PER_DAY = 8
SPRINT_WEEKS = 2

# Adjustments
HOLIDAYS = []  # Add dates as datetime.date(2024, 1, 1)
PLANNED_LEAVE = []  # Add leave days
MEETINGS_HOURS_PER_WEEK = 10
OTHER_COMMITMENTS_HOURS_PER_WEEK = 5

def calculate_capacity():
    """Calculate team capacity"""
    
    # Total available hours
    total_hours = TEAM_SIZE * WORKING_DAYS_PER_WEEK * HOURS_PER_DAY * SPRINT_WEEKS
    
    # Deductions
    holiday_hours = len(HOLIDAYS) * HOURS_PER_DAY * TEAM_SIZE
    leave_hours = len(PLANNED_LEAVE) * HOURS_PER_DAY
    meeting_hours = MEETINGS_HOURS_PER_WEEK * SPRINT_WEEKS
    other_hours = OTHER_COMMITMENTS_HOURS_PER_WEEK * SPRINT_WEEKS
    
    # Net capacity
    net_capacity = total_hours - holiday_hours - leave_hours - meeting_hours - other_hours
    
    print(f"Team Capacity Planning")
    print(f"=" * 50)
    print(f"Team Size: {{TEAM_SIZE}}")
    print(f"Sprint Duration: {{SPRINT_WEEKS}} weeks")
    print(f"")
    print(f"Total Available Hours: {{total_hours}}")
    print(f"Holiday Hours: -{{holiday_hours}}")
    print(f"Leave Hours: -{{leave_hours}}")
    print(f"Meeting Hours: -{{meeting_hours}}")
    print(f"Other Commitments: -{{other_hours}}")
    print(f"")
    print(f"NET CAPACITY: {{net_capacity}} hours")
    print(f"NET CAPACITY: {{net_capacity / HOURS_PER_DAY:.1f}} person-days")
    print(f"")
    print(f"Generated by Echo DevOps Master Suite 🌙")

if __name__ == "__main__":
    calculate_capacity()
'''
        return script, ScriptType.PYTHON
    
    def _risk_assessment(self, **kwargs) -> Tuple[str, ScriptType]:
        """Generate risk assessment template"""
        script = '''# Risk Assessment
# Generated by Echo 🌙

## Risk Register

| ID | Risk Description | Probability | Impact | Score | Mitigation Strategy | Owner | Status |
|----|------------------|-------------|--------|-------|---------------------|-------|--------|
| R1 | {{RISK_DESC}} | {{HIGH/MED/LOW}} | {{HIGH/MED/LOW}} | {{SCORE}} | {{MITIGATION}} | {{OWNER}} | {{STATUS}} |

## Risk Scoring
- **Probability**: High (3), Medium (2), Low (1)
- **Impact**: High (3), Medium (2), Low (1)
- **Score**: Probability × Impact

## Risk Response Plans

### High Priority Risks (Score >= 6)
{{RESPONSE_PLAN}}

### Medium Priority Risks (Score 3-5)
{{RESPONSE_PLAN}}

### Low Priority Risks (Score <= 2)
{{RESPONSE_PLAN}}

## Review Schedule
- **Next Review Date**: {{DATE}}
- **Review Frequency**: {{FREQUENCY}}

---
*Generated by Echo DevOps Master Suite*
'''
        return script, ScriptType.YAML
    
    def _default(self, **kwargs) -> Tuple[str, ScriptType]:
        """Default planning script"""
        script = '''#!/usr/bin/env bash
# Default planning script
# Generated by Echo 🌙

echo "Planning task - customize this script for your needs"
'''
        return script, ScriptType.BASH


__all__ = ["PlanGenerator"]
