"""
Module Generator
Produces a complete MasterChief addon zip:
  slug/
    app.py          Flask entry point (mc_launcher compatible, PROXY_BASE safe)
    plugin.py       Data fetcher for selected features
    template.html   Jinja2 display template
    requirements.txt
    README.md
"""
import zipfile
import textwrap
from pathlib import Path
from typing import Dict, List

PACKAGE_META = {
    'psutil':     {'label': 'System Monitor',   'icon': '📊', 'color': '#00ff88'},
    'kubernetes': {'label': 'Kubernetes',         'icon': '⎈',  'color': '#326CE5'},
    'docker':     {'label': 'Docker Manager',     'icon': '🐳', 'color': '#2496ED'},
    'boto3':      {'label': 'AWS Manager',        'icon': '☁',  'color': '#FF9900'},
    'redis':      {'label': 'Redis Explorer',     'icon': '🔴', 'color': '#DC382C'},
    'paramiko':   {'label': 'SSH Manager',        'icon': '🔐', 'color': '#f5a623'},
    'requests':   {'label': 'HTTP Client',        'icon': '🌐', 'color': '#58a6ff'},
    'sqlalchemy': {'label': 'Database Explorer',  'icon': '🗄',  'color': '#a78bfa'},
    'celery':     {'label': 'Task Queue',         'icon': '⚙',  'color': '#37b24d'},
    'flask':      {'label': 'Flask Inspector',    'icon': '🌶',  'color': '#ff6b35'},
    'fastapi':    {'label': 'FastAPI Inspector',  'icon': '⚡', 'color': '#009688'},
    'pandas':     {'label': 'Data Explorer',      'icon': '🐼', 'color': '#e91e63'},
    'numpy':      {'label': 'NumPy Console',      'icon': '🔢', 'color': '#4dabf7'},
}


def generate_module(pip_name: str, slug: str, features: List[str], output_dir: Path) -> Dict:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    mod_dir = output_dir / slug
    mod_dir.mkdir(exist_ok=True)

    meta = PACKAGE_META.get(pip_name, {
        'label': pip_name.replace('_',' ').replace('-',' ').title(),
        'icon':  '📦',
        'color': '#f5a623',
    })

    files = {
        'app.py':           _app_py(pip_name, slug, meta),
        'plugin.py':        _plugin_py(pip_name, slug, meta, features),
        'template.html':    _template_html(pip_name, meta),
        'requirements.txt': f'{pip_name}\nflask\n',
        'README.md':        _readme(pip_name, slug, meta, features),
    }

    for fname, content in files.items():
        (mod_dir / fname).write_text(content, encoding='utf-8')

    zip_path = output_dir / f'{slug}.zip'
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        for fname in files:
            zf.write(mod_dir / fname, arcname=f'{slug}/{fname}')

    return {
        'success':       True,
        'slug':          slug,
        'files_created': list(files.keys()),
        'zip_path':      str(zip_path),
        'file_count':    len(files),
    }


# ── app.py template ───────────────────────────────────────────
def _app_py(pip_name, slug, meta):
    label = meta['label']
    icon  = meta['icon']
    color = meta['color']
    # All curly braces that should be literal Python/JS must be doubled
    # {label} {icon} {color} are f-string substitutions
    return f'''\
"""
{label} — MasterChief Addon
Entry point for mc_launcher.py  /  auto-generated by Module System
"""
import os
from pathlib import Path
from flask import Flask, jsonify, render_template_string

app = Flask(__name__)

BASE_DIR   = Path(__file__).parent
ADDON_NAME = os.environ.get("MC_ADDON_NAME", BASE_DIR.name)
PROXY_BASE = f"/addons/modules/{{ADDON_NAME}}/app"

try:
    from plugin import get_data, PLUGIN_META
except ImportError as e:
    def get_data(): return {{"error": str(e)}}
    PLUGIN_META = {{"label": "{label}", "icon": "{icon}", "color": "{color}"}}

_tmpl_file = BASE_DIR / "template.html"
TEMPLATE   = _tmpl_file.read_text(encoding="utf-8") if _tmpl_file.exists() else "<p>{{{{ data }}}}</p>"

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>{{title}}</title>
<link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Unbounded:wght@400;700;900&display=swap" rel="stylesheet"/>
<style>
*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
:root{{--bg:#060809;--panel:#0a0d10;--card:#0e1419;--border:#1a2535;
  --accent:{{accent}};--text:#cdd6e0;--dim:#4a6070;--mid:#7a9ab0;
  --mono:"Space Mono",monospace;--ui:"Unbounded",sans-serif}}
body{{background:var(--bg);color:var(--text);font-family:var(--mono);font-size:13px;min-height:100vh}}
header{{display:flex;align-items:center;gap:16px;padding:0 32px;height:52px;
  background:var(--panel);border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100}}
.logo{{font-family:var(--ui);font-size:11px;font-weight:900;letter-spacing:.3em}}
.logo span{{color:var(--accent)}}
.refresh{{margin-left:auto;background:var(--accent);color:#000;font-family:var(--mono);
  font-size:10px;font-weight:700;letter-spacing:.15em;padding:7px 16px;border:none;
  border-radius:2px;cursor:pointer;transition:opacity .15s}}
.refresh:hover{{opacity:.8}}
main{{max-width:1200px;margin:0 auto;padding:32px}}
.hero-tag{{font-size:10px;letter-spacing:.4em;color:var(--accent);margin-bottom:6px}}
h1{{font-family:var(--ui);font-size:clamp(28px,4vw,48px);font-weight:900;
  -webkit-text-stroke:2px var(--accent);color:transparent;margin-bottom:24px;line-height:1}}
.data-area{{min-height:200px}}
.loading{{color:var(--dim);text-align:center;padding:60px;font-size:12px}}
.gen-error{{background:rgba(255,68,68,.05);border:1px solid rgba(255,68,68,.2);
  color:#ff4444;padding:12px;border-radius:2px;font-size:12px}}
.gen-section{{background:var(--card);border:1px solid var(--border);
  border-left:3px solid var(--accent);padding:18px;border-radius:2px;margin-bottom:14px}}
.gen-section-label{{font-size:9px;letter-spacing:.3em;color:var(--accent);margin-bottom:10px;font-weight:700}}
.gen-table{{width:100%;border-collapse:collapse;font-size:11px}}
.gen-table th{{text-align:left;padding:6px 8px;border-bottom:1px solid var(--border);
  color:var(--dim);font-size:9px;letter-spacing:.12em}}
.gen-table td{{padding:6px 8px;border-bottom:1px solid rgba(26,37,53,.5);color:var(--text);
  word-break:break-all;max-width:300px}}
.gen-table-wrap{{overflow-x:auto}}
.gen-stats-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:10px}}
.gen-stat{{background:var(--panel);border:1px solid var(--border);padding:12px;border-radius:2px}}
.gen-stat-label{{font-size:9px;letter-spacing:.12em;color:var(--dim);margin-bottom:4px}}
.gen-stat-val{{font-size:18px;font-weight:700}}
.gen-raw{{font-size:11px;color:var(--mid);line-height:1.6;background:var(--panel);
  padding:12px;border-radius:2px;white-space:pre-wrap;word-break:break-all}}
.gen-log{{font-size:11px;line-height:1.8;max-height:280px;overflow-y:auto}}
.gen-log-line{{padding:2px 0;border-bottom:1px solid rgba(26,37,53,.3);color:var(--mid)}}
.gen-empty{{color:var(--dim);text-align:center;padding:40px;font-size:12px}}
</style>
</head>
<body>
<header>
  <div class="logo"><span>[</span>{{title}}<span>]</span></div>
  <button class="refresh" onclick="loadData()">↺ REFRESH</button>
</header>
<main>
  <div class="hero-tag">// {pip_name.upper()}</div>
  <h1>{{title}}</h1>
  <div class="data-area" id="data-area"><div class="loading">Loading…</div></div>
</main>
<script>
(function(){{
  var m = window.location.pathname.match(/^([/]addons[/]modules[/][^/]+[/]app)/)/);
  window.PROXY_BASE = m ? m[1] : "";
}})();
async function loadData() {{
  var area = document.getElementById("data-area");
  area.innerHTML = "<div class=\\"loading\\">Fetching…</div>";
  try {{
    var r = await fetch(window.PROXY_BASE + "/api/data");
    var d = await r.json();
    area.innerHTML = d.html || "<div class=\\"gen-error\\">No data returned</div>";
  }} catch(e) {{
    area.innerHTML = "<div class=\\"gen-error\\">Error: " + e.message + "</div>";
  }}
}}
loadData();
</script>
</body></html>"""


@app.route("/")
def index():
    html = (PAGE
        .replace("{{title}}", PLUGIN_META.get("label", "{label}"))
        .replace("{{accent}}", PLUGIN_META.get("color", "{color}"))
    )
    return html


@app.route("/api/data")
def api_data():
    try:
        data     = get_data()
        rendered = render_template_string(TEMPLATE, data=data)
        return jsonify({{"html": rendered, "raw": data}})
    except Exception as e:
        return jsonify({{"html": f"<div class=\\"gen-error\\">{{e}}</div>", "error": str(e)}})


@app.route("/api/raw")
def api_raw():
    try:
        return jsonify(get_data())
    except Exception as e:
        return jsonify({{"error": str(e)}})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 9200))
    print(f"[{label}] Starting on http://localhost:{{port}}", flush=True)
    print(f"[{label}] Proxy base: {{PROXY_BASE}}", flush=True)
    app.run(host="0.0.0.0", port=port, debug=False)
'''


# ── plugin.py template ────────────────────────────────────────
def _plugin_py(pip_name, slug, meta, features):
    label = meta['label']
    icon  = meta['icon']
    color = meta['color']
    short = pip_name.split('.')[0]

    # Build each try block at exactly 4-space indent (inside get_data body)
    blocks = []
    for feat in features[:30]:
        key = feat.replace('.', '_').replace('-', '_')
        blocks.append(
            f'    # {feat}\n'
            f'    try:\n'
            f'        result = {feat}\n'
            f'        if hasattr(result, "_asdict"):\n'
            f'            data["{key}"] = dict(result._asdict())\n'
            f'        elif hasattr(result, "to_dict"):\n'
            f'            data["{key}"] = result.to_dict()\n'
            f'        elif hasattr(result, "__iter__") and not isinstance(result, (str,bytes)):\n'
            f'            data["{key}"] = [str(i) for i in list(result)[:50]]\n'
            f'        else:\n'
            f'            data["{key}"] = str(result)\n'
            f'    except Exception as e:\n'
            f'        data["{key}_error"] = str(e)\n'
        )

    body = '\n'.join(blocks) if blocks else '    pass\n'

    return (
        f'"""\n{label} Plugin — auto-generated by Module System\nPackage: {pip_name}\n"""\n\n'
        f'PLUGIN_META = {{\n'
        f'    "label":   "{label}",\n'
        f'    "icon":    "{icon}",\n'
        f'    "color":   "{color}",\n'
        f'    "package": "{pip_name}",\n'
        f'}}\n\n\n'
        f'def get_data() -> dict:\n'
        f'    """Fetch live data from {pip_name}."""\n'
        f'    try:\n'
        f'        import {short}\n'
        f'    except ImportError:\n'
        f'        return {{"error": "{pip_name} not installed — run: pip install {pip_name}"}}\n\n'
        f'    data = {{}}\n\n'
        f'{body}\n'
        f'    return data\n'
    )


# ── template.html ─────────────────────────────────────────────
def _template_html(pip_name, meta):
    color = meta['color']
    return textwrap.dedent(f"""\
        {{%- if data is mapping and data.get('error') -%}}
        <div class="gen-error">⚠ {{{{ data.error }}}}</div>
        {{%- elif data is mapping -%}}
        <div class="gen-stats-grid" style="margin-bottom:16px">
        {{%- for key, val in data.items() if not key.endswith('_error') -%}}
          <div class="gen-stat" style="border-left:3px solid {color}">
            <div class="gen-stat-label">{{{{ key | upper | replace('_',' ') }}}}</div>
            <div class="gen-stat-val" style="font-size:13px;word-break:break-all">
              {{{{- val | string | truncate(80) if val is not none else 'N/A' -}}}}
            </div>
          </div>
        {{%- endfor -%}}
        {{%- for key, val in data.items() if key.endswith('_error') -%}}
          <div class="gen-stat" style="border-left:3px solid #ff4444">
            <div class="gen-stat-label" style="color:#ff4444">{{{{ key | upper }}}}</div>
            <div style="font-size:10px;color:#ff4444">{{{{ val }}}}</div>
          </div>
        {{%- endfor -%}}
        </div>
        {{%- else -%}}
        <div class="gen-empty">No data returned from {pip_name}</div>
        {{%- endif -%}}
    """)


# ── README.md ─────────────────────────────────────────────────
def _readme(pip_name, slug, meta, features):
    label = meta['label']
    return textwrap.dedent(f"""\
        # {label}

        Auto-generated MasterChief addon for `{pip_name}`.

        ## Files
        - `app.py` — Flask entry point, launched by mc_launcher
        - `plugin.py` — Live data fetcher ({len(features)} features)
        - `template.html` — Jinja2 display template
        - `requirements.txt` — Dependencies

        ## Features ({len(features)})
        {chr(10).join(f'- {f}' for f in features[:40])}
        {'...' if len(features) > 40 else ''}

        ## Access
        After install: `/addons/modules/{slug}/app/`
    """)
