import os
from jinja2 import Environment, FileSystemLoader
import io
import zipfile
import json
from .schema import ModuleSpec

HERE = os.path.dirname(__file__)
env = Environment(loader=FileSystemLoader(os.path.join(HERE, "templates")), trim_blocks=True, lstrip_blocks=True)


def validate_spec(spec: dict):
    # Use pydantic ModuleSpec for validation and conversion
    if not isinstance(spec, dict):
        raise ValueError("Spec must be a JSON object")
    ms = ModuleSpec(**spec)
    return ms


def render_template(name: str, context: dict) -> str:
    tmpl = env.get_template(name)
    return tmpl.render(**context)


def tf_type_from_spec(t) -> str:
    """Infer a Terraform type string from a JSON Schema type or shorthand.

    Accepts either a string (e.g. 'string') or a dict describing a schema (with 'type', 'items', 'properties').
    """
    # if a dict-like schema provided
    if isinstance(t, dict):
        js_type = t.get('type')
        if js_type == 'array':
            items = t.get('items', {})
            item_tf = tf_type_from_spec(items) if items else 'any'
            return f'list({item_tf})'
        if js_type == 'object':
            props = t.get('properties') or {}
            if props:
                # build typed object(...) spec
                parts = []
                for k, v in props.items():
                    parts.append(f'{k} = {tf_type_from_spec(v)}')
                inner = ', '.join(parts)
                return f'object({{{inner}}})'
            return 'map(any)'
        # fallback to string/primitive handling below
        t = js_type or 'string'

    if not t:
        return 'string'
    t = str(t).strip()
    # pass-through complex terraform types
    if '(' in t or t.startswith('map') or t.startswith('list') or t.startswith('object('):
        return t
    mapping = {
        'string': 'string',
        'str': 'string',
        'number': 'number',
        'int': 'number',
        'integer': 'number',
        'bool': 'bool',
        'boolean': 'bool',
        'object': 'map(any)',
        'list': 'list(string)',
        'map': 'map(any)',
        'any': 'any',
    }
    return mapping.get(t.lower(), 'string')


def generate_files(spec: dict) -> dict:
    ms = validate_spec(spec)
    # Normalize variables with Terraform type strings
    vars_out = []
    for v in ms.variables:
        d = v.model_dump()
        d['tf_type'] = tf_type_from_spec(d.get('type') or '')
        vars_out.append(d)

    ctx = {
        "module_name": ms.module_name,
        "provider": ms.provider,
        "variables": vars_out,
        "resources": [r.model_dump() for r in ms.resources],
        "outputs": [o.model_dump() for o in ms.outputs],
    }

    # render provider-specific block if template exists
    try:
        provider_block = render_template(f"providers/{ms.provider}.tf.j2", ctx)
    except Exception:
        provider_block = ''
    ctx['provider_block'] = provider_block

    files = {}
    files["main.tf"] = render_template("main.tf.j2", ctx)
    files["variables.tf"] = render_template("variables.tf.j2", ctx)
    files["outputs.tf"] = render_template("outputs.tf.j2", ctx)
    files["README.md"] = f"# {ctx['module_name']}\n\nGenerated by TF Wizard.\n"
    return files


def generate_module_zip(spec: dict) -> bytes:
    files = generate_files(spec)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for path, content in files.items():
            z.writestr(path, content)
    buf.seek(0)
    return buf.read()


if __name__ == "__main__":
    example = {
        "module_name": "example",
        "provider": "aws",
        "variables": [{"name": "region", "type": "string", "default": "us-east-1", "description": "AWS region"}],
        "resources": [{"type": "aws_s3_bucket", "name": "bucket", "args": {"bucket": "${var.module_name}-bucket"}}],
        "outputs": [{"name": "bucket_id", "value": "aws_s3_bucket.bucket.id"}],
    }
    b = generate_module_zip(example)
    print(len(b))
