"""
Module Generator
Produces a zip containing a complete MasterChief addon module:
  slug/
    app.py          — Flask entry point (PROXY_BASE aware)
    plugin.py       — data fetcher using selected features
    template.html   — Jinja2 data display template
    requirements.txt
    README.md
"""
import json
import zipfile
import textwrap
from pathlib import Path
from typing import Dict, List

PACKAGE_META = {
    'psutil':      {'label': 'System Monitor',   'icon': '📊', 'color': '#00ff88'},
    'kubernetes':  {'label': 'Kubernetes',         'icon': '⎈',  'color': '#326CE5'},
    'docker':      {'label': 'Docker Manager',     'icon': '🐳', 'color': '#2496ED'},
    'boto3':       {'label': 'AWS Manager',        'icon': '☁',  'color': '#FF9900'},
    'redis':       {'label': 'Redis Explorer',     'icon': '🔴', 'color': '#DC382C'},
    'paramiko':    {'label': 'SSH Manager',        'icon': '🔐', 'color': '#f5a623'},
    'requests':    {'label': 'HTTP Client',        'icon': '🌐', 'color': '#58a6ff'},
    'sqlalchemy':  {'label': 'Database Explorer',  'icon': '🗄',  'color': '#a78bfa'},
    'celery':      {'label': 'Task Queue',         'icon': '⚙',  'color': '#37b24d'},
}


def generate_module(
    pip_name: str,
    slug: str,
    features: List[str],
    output_dir: Path,
) -> Dict:
    """
    Generate a module zip.
    Returns: {success, slug, files_created, zip_path, file_count}
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    mod_dir = output_dir / slug
    mod_dir.mkdir(exist_ok=True)

    meta = PACKAGE_META.get(pip_name, {
        'label': pip_name.replace('_', ' ').replace('-', ' ').title(),
        'icon':  '📦',
        'color': '#f5a623',
    })

    files = {
        'app.py':          _gen_app_py(pip_name, slug, meta),
        'plugin.py':       _gen_plugin_py(pip_name, slug, meta, features),
        'template.html':   _gen_template_html(pip_name, meta),
        'requirements.txt': f'{pip_name}\nflask\n',
        'README.md':       _gen_readme(pip_name, slug, meta, features),
    }

    created = []
    for fname, content in files.items():
        (mod_dir / fname).write_text(content, encoding='utf-8')
        created.append(fname)

    zip_path = output_dir / f'{slug}.zip'
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        for fname in files:
            zf.write(mod_dir / fname, arcname=f'{slug}/{fname}')

    return {
        'success':       True,
        'slug':          slug,
        'files_created': created,
        'zip_path':      str(zip_path),
        'file_count':    len(files),
    }


# ── File generators ───────────────────────────────────────────

def _gen_app_py(pip_name: str, slug: str, meta: Dict) -> str:
    label = meta['label']
    icon  = meta['icon']
    color = meta['color']
    return f'''"""
{label} — MasterChief Addon
Entry point for mc_launcher.py
Auto-generated by Module System v3
"""
import os
from pathlib import Path
from flask import Flask, jsonify, render_template_string

app = Flask(__name__)

# PROXY_BASE: all URLs must go through this path, never use raw port
BASE_DIR   = Path(__file__).parent
ADDON_NAME = os.environ.get('MC_ADDON_NAME', BASE_DIR.name)
PROXY_BASE = f'/addons/modules/{{ADDON_NAME}}/app'

try:
    from plugin import get_data, PLUGIN_META
except ImportError as e:
    def get_data(): return {{"error": str(e)}}
    PLUGIN_META = {{"label": "{label}", "icon": "{icon}", "color": "{color}"}}

TEMPLATE_FILE = BASE_DIR / "template.html"
TEMPLATE = TEMPLATE_FILE.read_text(encoding="utf-8") if TEMPLATE_FILE.exists() else "<p>{{{{ data }}}}</p>"

# Inline page — no url_for, no static files, PROXY_BASE injected
PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>{{title}}</title>
<link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Unbounded:wght@400;700;900&display=swap" rel="stylesheet"/>
<style>
*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
:root{{--bg:#060809;--panel:#0a0d10;--card:#0e1419;--border:#1a2535;
  --accent:{{accent}};--text:#cdd6e0;--dim:#4a6070;--mid:#7a9ab0;
  --mono:'Space Mono',monospace;--display:'Unbounded',sans-serif;}}
body{{background:var(--bg);color:var(--text);font-family:var(--mono);font-size:13px;min-height:100vh}}
header{{display:flex;align-items:center;gap:16px;padding:0 32px;height:52px;
  background:var(--panel);border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100}}
.logo{{font-family:var(--display);font-size:11px;font-weight:900;letter-spacing:.3em}}
.logo span{{color:var(--accent)}}
.refresh{{margin-left:auto;background:var(--accent);color:#000;font-family:var(--mono);
  font-size:10px;font-weight:700;letter-spacing:.15em;padding:7px 16px;border:none;
  border-radius:2px;cursor:pointer}}
main{{max-width:1200px;margin:0 auto;padding:32px}}
.error{{background:rgba(255,68,68,.05);border:1px solid rgba(255,68,68,.2);
  color:#ff4444;padding:12px;border-radius:2px;font-size:12px}}
</style>
</head>
<body>
<header>
  <div class="logo"><span>[</span>{{title}}<span>]</span></div>
  <button class="refresh" onclick="loadData()">↺ REFRESH</button>
</header>
<main>
  <div id="data-area" style="min-height:200px">
    <p style="color:var(--dim);text-align:center;padding:60px">Loading…</p>
  </div>
</main>
<script>
// PROXY_BASE injected at render time — never hardcode port
const BASE = "{{proxy_base}}";
async function loadData() {{
  const area = document.getElementById('data-area');
  area.innerHTML = '<p style="color:#4a6070;text-align:center;padding:40px">Fetching…</p>';
  try {{
    const r = await fetch(BASE + '/api/data');
    const d = await r.json();
    area.innerHTML = d.html || '<div class="error">No data</div>';
  }} catch(e) {{
    area.innerHTML = '<div class="error">Error: ' + e.message + '</div>';
  }}
}}
loadData();
</script>
</body>
</html>"""


@app.route('/')
def index():
    html = (PAGE
        .replace('{{title}}', PLUGIN_META.get('label', '{label}'))
        .replace('{{accent}}', PLUGIN_META.get('color', '{color}'))
        .replace('{{proxy_base}}', PROXY_BASE)
    )
    return html


@app.route('/api/data')
def api_data():
    try:
        data    = get_data()
        rendered = render_template_string(TEMPLATE, data=data)
        return jsonify({{"html": rendered, "raw": data}})
    except Exception as e:
        return jsonify({{"html": f'<div class="error">{{e}}</div>', "error": str(e)}})


@app.route('/api/raw')
def api_raw():
    try:
        return jsonify(get_data())
    except Exception as e:
        return jsonify({{"error": str(e)}})


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 9200))
    print(f'[{label}] Starting on http://localhost:{{port}}', flush=True)
    print(f'[{label}] Proxy base: {{PROXY_BASE}}', flush=True)
    app.run(host='0.0.0.0', port=port, debug=False)
'''


def _gen_plugin_py(pip_name: str, slug: str, meta: Dict, features: List[str]) -> str:
    label = meta['label']
    icon  = meta['icon']
    color = meta['color']

    # Build import and data-fetch sections
    short_name = pip_name.split('.')[0]
    import_line = f'import {short_name}'

    data_sections = []
    for feat_name in features[:20]:  # cap at 20 to keep file manageable
        short = feat_name.split('.')[-1]
        data_sections.append(
            f'    # {feat_name}\n'
            f'    try:\n'
            f'        result = str({feat_name})\n'
            f'        data["{short}"] = result\n'
            f'    except Exception as e:\n'
            f'        data["{short}_error"] = str(e)\n'
        )

    data_body = '\n'.join(data_sections) if data_sections else '    pass\n'

    return f'''"""
{label} Plugin
Data fetcher — auto-generated by Module System v3
Package: {pip_name}
Selected features: {len(features)}
"""
try:
    {import_line}
    _AVAILABLE = True
except ImportError as e:
    _AVAILABLE = False
    _IMPORT_ERROR = str(e)

PLUGIN_META = {{
    "label":   "{label}",
    "icon":    "{icon}",
    "color":   "{color}",
    "package": "{pip_name}",
}}


def get_data() -> dict:
    """Fetch data from {pip_name}. Returns dict of results."""
    if not _AVAILABLE:
        return {{"error": f"Package {pip_name} not available: {{_IMPORT_ERROR}}"}}

    data = {{}}

{data_body}
    return data
'''


def _gen_template_html(pip_name: str, meta: Dict) -> str:
    label = meta['label']
    color = meta['color']
    return f'''{{%- set error = data.get('error') if data is mapping else None -%}}
{{%- if error -%}}
<div style="background:rgba(255,68,68,.05);border:1px solid rgba(255,68,68,.2);color:#ff4444;padding:12px;border-radius:2px;font-size:12px">
  ⚠ {{{{ error }}}}
</div>
{{%- else -%}}
<div style="font-family:\'Space Mono\',monospace">
  <div style="margin-bottom:20px">
    <div style="font-size:10px;color:#4a6070;letter-spacing:.3em;margin-bottom:6px">// {pip_name.upper()}</div>
    <h2 style="font-family:\'Unbounded\',sans-serif;font-size:24px;font-weight:900;
               -webkit-text-stroke:2px {color};color:transparent">{label.upper()}</h2>
  </div>
  <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:10px">
    {{%- for key, val in (data.items() if data is mapping else {{}}.items()) -%}}
    <div style="background:#0e1419;border:1px solid #1a2535;border-left:3px solid {color};
                padding:12px;border-radius:2px">
      <div style="font-size:9px;color:#4a6070;letter-spacing:.15em;margin-bottom:4px">
        {{{{ key | upper | replace(\'_\', \' \') }}}}
      </div>
      <div style="font-size:12px;word-break:break-all;color:#cdd6e0">
        {{{{ val | truncate(120) if val is string else val | string | truncate(120) }}}}
      </div>
    </div>
    {{%- endfor -%}}
  </div>
</div>
{{%- endif -%}}
'''


def _gen_readme(pip_name: str, slug: str, meta: Dict, features: List[str]) -> str:
    label = meta['label']
    return textwrap.dedent(f'''\
    # {label}

    Auto-generated MasterChief addon module for `{pip_name}`.

    ## Files

    - `app.py` — Flask entry point, launched by mc_launcher
    - `plugin.py` — Data fetcher ({len(features)} features selected)
    - `template.html` — Jinja2 display template
    - `requirements.txt` — Dependencies

    ## Selected Features ({len(features)})

    {chr(10).join(f"- {f}" for f in features[:30])}
    {"..." if len(features) > 30 else ""}

    ## Setup

    1. Install dependencies: `pip install {pip_name}`
    2. Module starts automatically when loaded by MasterChief addon manager
    3. Access via: `/addons/modules/{slug}/app/`

    Generated by Module System v3
    ''')
