version: '3.8'
services:
  inspircd:
    image: inspircd/inspircd-docker:latest
    container_name: inspircd
    ports:
      - "6667:6667"
      - "6697:6697"
    volumes:
      - ../data/inspircd_conf:/inspircd/conf
    restart: unless-stopped

  anope:
    image: anope/anope:latest
    container_name: anope
    volumes:
      - ../data/anope_conf:/anope/conf
    restart: unless-stopped
    depends_on:
      - inspircd

networks:
  default:
    driver: bridge
