#!/bin/bash
# Generate Anope and InspIRCd link configs and bring up docker-compose stack
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ANOPE_DIR="$ROOT_DIR/data/anope_conf"
INSP_DIR="$ROOT_DIR/data/inspircd_conf"
COMPOSE_FILE="$ROOT_DIR/tools/irc_stack_compose.yml"

mkdir -p "$ANOPE_DIR" "$INSP_DIR"

PW_FILE="$ROOT_DIR/data/irc_service_passwords.json"
if [ -f "$PW_FILE" ]; then
  echo "Using existing passwords in $PW_FILE"
  cat "$PW_FILE"
else
  S_PASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 24)
  R_PASS=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 24)
  jq -n --arg s "$S_PASS" --arg r "$R_PASS" '{services_send:$s, services_recv:$r}' > "$PW_FILE" || echo "{\"services_send\":\"$S_PASS\",\"services_recv\":\"$R_PASS\"}" > "$PW_FILE"
  echo "Generated passwords and stored in $PW_FILE"
fi

if command -v jq >/dev/null 2>&1; then
  SERV_SEND=$(jq -r .services_send "$PW_FILE")
  SERV_RECV=$(jq -r .services_recv "$PW_FILE")
elif command -v python >/dev/null 2>&1 || command -v python3 >/dev/null 2>&1; then
  PY=$(command -v python || command -v python3)
  SERV_SEND=$($PY -c "import json,sys
f=sys.argv[1]
print(json.load(open(f))['services_send'])" "$PW_FILE")
  SERV_RECV=$($PY -c "import json,sys
f=sys.argv[1]
print(json.load(open(f))['services_recv'])" "$PW_FILE")
else
  echo "ERROR: 'jq' or 'python' is required to read $PW_FILE. Install jq or ensure python is on PATH." >&2
  exit 1
fi

echo "Writing Anope template to $ANOPE_DIR/services.conf"
cat > "$ANOPE_DIR/services.conf" <<EOF
; Anope services generated by MasterChief
[services]
name = "Anope"
host = "inspircd"
port = 6669
password = "$SERV_RECV"

[chanserv]
enable = yes

[nickserv]
enable = yes

EOF

echo "Writing Inspircd link fragment to $INSP_DIR/link.conf"
cat > "$INSP_DIR/link.conf" <<EOF
<link name="anope" sendpass="$SERV_SEND" recvpass="$SERV_RECV" host="anope" port="6669" />
<module name="m_services" />
EOF

echo "Starting Docker Compose stack..."
docker compose -f "$COMPOSE_FILE" up -d
echo "Stack started. Check logs: docker logs -f inspircd" 
