<#
Windows PowerShell version of tools/setup_irc_stack.sh
Generates service passwords, writes Anope/InspIRCd fragments under data/, and starts docker compose.
#>
Param()
Set-StrictMode -Version Latest

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Definition)
$anopeDir = Join-Path $root 'data\anope_conf'
$inspDir  = Join-Path $root 'data\inspircd_conf'
$composeFile = Join-Path $root 'tools\irc_stack_compose.yml'

New-Item -ItemType Directory -Path $anopeDir -Force | Out-Null
New-Item -ItemType Directory -Path $inspDir -Force | Out-Null

$pwFile = Join-Path $root 'data\irc_service_passwords.json'
if (Test-Path $pwFile) {
    Write-Host "Using existing passwords in $pwFile"
    Get-Content $pwFile | Write-Host
} else {
    # generate random 24-char alphanumeric strings
    function New-RandomString($length){
        $chars = ([char[]]([char]'A'..[char]'Z')) + ([char[]]([char]'a'..[char]'z')) + ([char[]]([char]'0'..[char]'9'))
        -join (1..$length | ForEach-Object { $chars | Get-Random })
    }
    $s_pass = New-RandomString 24
    $r_pass = New-RandomString 24
    $obj = @{ services_send = $s_pass; services_recv = $r_pass }
    $obj | ConvertTo-Json | Out-File -Encoding UTF8 $pwFile
    Write-Host "Generated passwords and stored in $pwFile"
}

# Read passwords
$json = Get-Content $pwFile -Raw | ConvertFrom-Json
$serv_send = $json.services_send
$serv_recv = $json.services_recv

Write-Host "Writing Anope template to $anopeDir\services.conf"
@"
; Anope services generated by MasterChief
[services]
name = "Anope"
host = "inspircd"
port = 6669
password = "$serv_recv"

[chanserv]
enable = yes

[nickserv]
enable = yes

"@ | Out-File -Encoding UTF8 (Join-Path $anopeDir 'services.conf')

Write-Host "Writing Inspircd link fragment to $inspDir\link.conf"
@"
<link name="anope" sendpass="$serv_send" recvpass="$serv_recv" host="anope" port="6669" />
<module name="m_services" />
"@ | Out-File -Encoding UTF8 (Join-Path $inspDir 'link.conf')

Write-Host "Starting Docker Compose stack..."
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Error "Docker is not available on PATH. Install Docker Desktop and ensure 'docker' is on PATH."
    exit 1
}

$composeCmd = "docker compose -f `"$composeFile`" up -d"
Write-Host $composeCmd
Invoke-Expression $composeCmd
Write-Host "Stack started. Check logs: docker logs -f inspircd"
