"""
Module Scaffold Generator
Given a package name + selected feature IDs, generates:
  - plugin.py
  - template.html
  - requirements.txt
  - README.md
Then zips the whole thing.
"""
import os
import zipfile
import json
import re
from pathlib import Path
from datetime import datetime
from introspector import introspect_package, get_import_name


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_")


def generate_module(
    pip_name: str,
    selected_feature_ids: list,
    meta: dict,
    output_dir: Path,
) -> dict:
    """
    Generate all scaffold files for a module.
    Returns {success, files_created, zip_path}
    """
    introspection = introspect_package(pip_name)
    if "error" in introspection:
        return {"success": False, "error": introspection["error"]}

    all_features = {f["id"]: f for f in introspection["features"]}
    selected = [all_features[fid] for fid in selected_feature_ids if fid in all_features]

    if not selected:
        return {"success": False, "error": "No valid features selected"}

    slug = slugify(pip_name)
    mod_dir = output_dir / slug
    mod_dir.mkdir(parents=True, exist_ok=True)

    files = {}

    # 1. app.py  ← Flask entry point launched by mc_launcher
    files["app.py"] = _gen_app_py(pip_name, slug, meta)

    # 2. plugin.py
    files["plugin.py"] = _gen_plugin_py(pip_name, slug, selected, meta, introspection)

    # 3. template.html
    files["template.html"] = _gen_template_html(pip_name, slug, selected, meta)

    # 4. requirements.txt
    files["requirements.txt"] = _gen_requirements(pip_name)

    # 5. README.md
    files["README.md"] = _gen_readme(pip_name, slug, selected, meta)

    # Write files
    created = []
    for fname, content in files.items():
        fpath = mod_dir / fname
        fpath.write_text(content, encoding="utf-8")
        created.append(fname)

    # Zip it
    zip_path = output_dir / f"{slug}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname in files:
            zf.write(mod_dir / fname, arcname=f"{slug}/{fname}")

    return {
        "success": True,
        "slug": slug,
        "files_created": created,
        "zip_path": str(zip_path),
        "file_count": len(files),
    }


def _gen_app_py(pip_name, slug, meta):
    """Generate a Flask app.py entry point for the addon manager."""
    label = meta.get("label", pip_name.title())
    icon  = meta.get("icon", "🔧")
    color = meta.get("color", "#58a6ff")

    return f'''"""
{label} — DevOps Suite Addon
Entry point for mc_launcher.py
Auto-generated by Module Generator
"""
import os
from pathlib import Path
from flask import Flask, jsonify, render_template_string

app = Flask(__name__)

BASE_DIR  = Path(__file__).parent
PROXY_BASE = f"/addons/modules/{{BASE_DIR.name}}/app"

# Import the generated plugin
try:
    from plugin import get_data, PLUGIN_META
except ImportError as e:
    def get_data(): return {{"error": str(e)}}
    PLUGIN_META = {{"label": "{label}", "icon": "{icon}", "color": "{color}"}}

TEMPLATE = open(BASE_DIR / "template.html").read() if (BASE_DIR / "template.html").exists() else "<p>{{{{ data }}}}</p>"

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>{{title}}</title>
  <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Unbounded:wght@400;700;900&display=swap" rel="stylesheet">
  <style>
    *,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
    :root{{--bg:#060809;--panel:#0a0d10;--card:#0e1419;--border:#1a2535;
          --amber:#f5a623;--green:#00ff88;--red:#ff4444;--text:#cdd6e0;--dim:#4a6070;--mid:#7a9ab0;
          --mono:'Space Mono',monospace;--display:'Unbounded',sans-serif;}}
    body{{background:var(--bg);color:var(--text);font-family:var(--mono);font-size:13px;min-height:100vh}}
    header{{display:flex;align-items:center;gap:16px;padding:0 32px;height:52px;
            background:var(--panel);border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100}}
    .logo{{font-family:var(--display);font-size:11px;font-weight:900;letter-spacing:.3em}}
    .logo span{{color:var(--amber)}}
    main{{max-width:1200px;margin:0 auto;padding:40px 32px}}
    .hero{{margin-bottom:40px}}
    .hero-tag{{font-size:10px;letter-spacing:.4em;color:var(--amber);margin-bottom:8px}}
    h1{{font-family:var(--display);font-size:clamp(28px,4vw,52px);font-weight:900;line-height:1}}
    h1 em{{font-style:normal;-webkit-text-stroke:2px {{accent}};color:transparent}}
    .refresh-btn{{margin-left:auto;background:var(--amber);color:#000;font-family:var(--mono);
                  font-size:10px;font-weight:700;letter-spacing:.15em;padding:8px 16px;
                  border:none;border-radius:2px;cursor:pointer}}
    .refresh-btn:hover{{background:#ffc040}}
    .gen-section{{background:var(--card);border:1px solid var(--border);
                  border-left:3px solid {{accent}};padding:20px;border-radius:2px;margin-bottom:16px}}
    .gen-section-label{{font-size:9px;letter-spacing:.3em;color:var(--amber);margin-bottom:12px;font-weight:700}}
    .gen-table{{width:100%;border-collapse:collapse;font-size:11px}}
    .gen-table th{{text-align:left;padding:6px 8px;border-bottom:1px solid var(--border);
                   color:var(--dim);font-size:9px;letter-spacing:.15em}}
    .gen-table td{{padding:6px 8px;border-bottom:1px solid rgba(26,37,53,.5);color:var(--text)}}
    .gen-table-wrap{{overflow-x:auto}}
    .gen-stats-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:12px}}
    .gen-stat{{background:var(--panel);border:1px solid var(--border);padding:12px;border-radius:2px}}
    .gen-stat-label{{font-size:9px;letter-spacing:.15em;color:var(--dim);margin-bottom:4px}}
    .gen-stat-val{{font-size:18px;font-weight:700;color:var(--text)}}
    .gen-raw{{font-size:11px;color:var(--mid);line-height:1.6;
              background:var(--panel);padding:12px;border-radius:2px;white-space:pre-wrap;word-break:break-all}}
    .gen-log{{font-size:11px;line-height:1.8;max-height:300px;overflow-y:auto}}
    .gen-log-line{{padding:2px 0;border-bottom:1px solid rgba(26,37,53,.3);color:var(--mid)}}
    .gen-error{{color:var(--red);font-size:11px;padding:12px;background:rgba(255,68,68,.05);
                border:1px solid rgba(255,68,68,.2);border-radius:2px;margin-bottom:12px}}
    .gen-empty{{color:var(--dim);font-size:12px;text-align:center;padding:40px}}
    .loading{{color:var(--mid);font-size:12px;text-align:center;padding:40px}}
    .data-area{{min-height:200px}}
  </style>
</head>
<body>
<header>
  <div class="logo"><span>[</span>{{title}}<span>]</span></div>
  <button class="refresh-btn" onclick="loadData()">↺ REFRESH</button>
</header>
<main>
  <div class="hero">
    <div class="hero-tag">// {pip_name.upper()}</div>
    <h1>{{icon}} <em>{label.upper()}</em></h1>
  </div>
  <div class="data-area" id="dataArea"><div class="loading">Loading data...</div></div>
</main>
<script>
const BASE = "{{proxy_base}}";
async function loadData() {{
  const area = document.getElementById('dataArea');
  area.innerHTML = '<div class="loading">Fetching data...</div>';
  try {{
    const r = await fetch(BASE + '/api/data');
    const d = await r.json();
    if (d.html) {{ area.innerHTML = d.html; }}
    else {{ area.innerHTML = '<div class="gen-error">No data returned</div>'; }}
  }} catch(e) {{
    area.innerHTML = '<div class="gen-error">Error: ' + e.message + '</div>';
  }}
}}
loadData();
</script>
</body>
</html>"""

@app.route("/")
def index():
    html = PAGE.replace("{{title}}", PLUGIN_META.get("label", "{label}")) \\
               .replace("{{icon}}", PLUGIN_META.get("icon", "{icon}")) \\
               .replace("{{accent}}", PLUGIN_META.get("color", "{color}")) \\
               .replace("{{proxy_base}}", PROXY_BASE)
    return html


@app.route("/api/data")
def api_data():
    try:
        data = get_data()
        rendered = render_template_string(TEMPLATE, data=data)
        return jsonify({{"html": rendered, "raw": data}})
    except Exception as e:
        return jsonify({{"html": f\'<div class="gen-error">{{e}}</div>\', "error": str(e)}})


@app.route("/api/raw")
def api_raw():
    try:
        return jsonify(get_data())
    except Exception as e:
        return jsonify({{"error": str(e)}})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 9200))
    print(f"[{label}] Starting on http://localhost:{{port}}", flush=True)
    app.run(host="0.0.0.0", port=port, debug=False)
'''


# ─────────────────────────────────────────────
# FILE GENERATORS
# ─────────────────────────────────────────────

def _gen_plugin_py(pip_name, slug, features, meta, introspection):
    import_name = introspection["import_name"]
    label = meta.get("label", pip_name.title())
    icon = meta.get("icon", "🔧")
    color = meta.get("color", "#58a6ff")
    order = meta.get("order", 10)

    # Build get_data sections
    data_sections = []
    for f in features:
        method = f["method_path"]
        key = f["id"]
        data_type = f["data_type"]
        data_sections.append(f"""
        # {f['label']} — {f['description'][:80]}
        try:
            raw = {method}()
            if hasattr(raw, 'to_dict'):
                data['{key}'] = raw.to_dict()
            elif hasattr(raw, '__iter__') and not isinstance(raw, (str, bytes)):
                data['{key}'] = [item.to_dict() if hasattr(item, 'to_dict') else str(item) for item in raw]
            else:
                data['{key}'] = str(raw)
        except Exception as e:
            data['{key}_error'] = str(e)""")

    sections_code = "\n".join(data_sections)

    return f'''"""
{label} Plugin
Auto-generated by DevOps Suite Module Generator
Package: {pip_name}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}

Selected features: {", ".join(f["label"] for f in features)}
"""

PLUGIN_META = {{
    "label": "{label}",
    "icon": "{icon}",
    "description": "{meta.get("description", f"Auto-generated {pip_name} module")}",
    "order": {order},
    "color": "{color}",
    "package": "{pip_name}",
    "generated": True,
}}


def get_data():
    """Fetch data from {pip_name} for all selected features."""
    try:
        import {import_name}
    except ImportError:
        return {{"error": "{pip_name} not installed. Run: pip install {pip_name}"}}\n
    data = {{}}
    {sections_code}
    return data
'''


def _gen_template_html(pip_name, slug, features, meta):
    label = meta.get("label", pip_name.title())
    icon = meta.get("icon", "🔧")

    sections = []
    for f in features:
        key = f["id"]
        label_f = f["label"]
        data_type = f["data_type"]

        if data_type == "table":
            sections.append(f"""
{{% if data.get('{key}') %}}
<div class="gen-section">
  <div class="gen-section-label">{label_f.upper()}</div>
  <div class="gen-table-wrap">
    <table class="gen-table">
      <thead>
        <tr>
          {{% for col in (data['{key}'][0].keys() if data['{key}'] and isinstance(data['{key}'][0], dict) else ['Value']) %}}
          <th>{{{{ col }}}}</th>
          {{% endfor %}}
        </tr>
      </thead>
      <tbody>
        {{% for row in data['{key}'] %}}
        <tr>
          {{% if row is mapping %}}
            {{% for v in row.values() %}}<td>{{{{ v }}}}</td>{{% endfor %}}
          {{% else %}}
            <td>{{{{ row }}}}</td>
          {{% endif %}}
        </tr>
        {{% endfor %}}
      </tbody>
    </table>
  </div>
</div>
{{% elif data.get('{key}_error') %}}
<div class="gen-error">{label_f}: {{{{ data['{key}_error'] }}}}</div>
{{% endif %}}""")

        elif data_type == "stats":
            sections.append(f"""
{{% if data.get('{key}') %}}
<div class="gen-section">
  <div class="gen-section-label">{label_f.upper()}</div>
  <div class="gen-stats-grid">
    {{% if data['{key}'] is mapping %}}
      {{% for k, v in data['{key}'].items() %}}
      <div class="gen-stat">
        <div class="gen-stat-label">{{{{ k }}}}</div>
        <div class="gen-stat-val">{{{{ v }}}}</div>
      </div>
      {{% endfor %}}
    {{% else %}}
      <div class="gen-stat-raw">{{{{ data['{key}'] }}}}</div>
    {{% endif %}}
  </div>
</div>
{{% endif %}}""")

        elif data_type == "log":
            sections.append(f"""
{{% if data.get('{key}') %}}
<div class="gen-section">
  <div class="gen-section-label">{label_f.upper()}</div>
  <div class="gen-log">
    {{% for line in (data['{key}'] if data['{key}'] is iterable and data['{key}'] is not string else [data['{key}']]) %}}
    <div class="gen-log-line">{{{{ line }}}}</div>
    {{% endfor %}}
  </div>
</div>
{{% endif %}}""")

        else:
            sections.append(f"""
{{% if data.get('{key}') is not none %}}
<div class="gen-section">
  <div class="gen-section-label">{label_f.upper()}</div>
  <div class="gen-raw">{{{{ data['{key}'] }}}}</div>
</div>
{{% endif %}}""")

    all_sections = "\n".join(sections)

    return f"""{{%- if data.get('error') %}}
<div class="gen-error">{{{{ data.error }}}}</div>
{{%- else %}}
{all_sections}
{{%- if not data %}}
<div class="gen-empty">No data returned from {label}</div>
{{%- endif %}}
{{%- endif %}}
"""


def _gen_requirements(pip_name):
    return f"{pip_name}\n"


def _gen_readme(pip_name, slug, features, meta):
    label = meta.get("label", pip_name.title())
    feature_list = "\n".join(
        f"- **{f['label']}** (`{f['method_path']}`) — {f['description'][:100]}"
        for f in features
    )
    return f"""# {label} Module

Auto-generated DevOps Suite module for `{pip_name}`.

## Installation

```bash
pip install {pip_name}
```

Then upload `{slug}.zip` via the Module Manager UI.

## Selected Features

{feature_list}

## Files

| File | Purpose |
|------|---------|
| `plugin.py` | Data fetcher — implements `get_data()` |
| `template.html` | Jinja2 UI for the dashboard card |
| `requirements.txt` | Pip dependencies |
| `README.md` | This file |

## Usage

Once installed, navigate to the dashboard and enable the **{label}** module
using the sidebar toggle. The module will load its UI automatically.

## Customization

Edit `plugin.py` to add authentication, environment variables, or
custom data transformations. Edit `template.html` to change the UI layout.

---
*Generated {datetime.now().strftime("%Y-%m-%d")} by DevOps Suite Module Generator*
"""
