"""
Kubernetes — DevOps Suite Addon
Entry point for mc_launcher.py
Auto-generated by Module Generator
"""
import os
from pathlib import Path
from flask import Flask, jsonify, render_template_string

app = Flask(__name__)

BASE_DIR  = Path(__file__).parent
PROXY_BASE = f"/addons/modules/{BASE_DIR.name}/app"

# Import the generated plugin
try:
    from plugin import get_data, PLUGIN_META
except ImportError as e:
    def get_data(): return {"error": str(e)}
    PLUGIN_META = {"label": "Kubernetes", "icon": "☸️", "color": "#326ce5"}

TEMPLATE = open(BASE_DIR / "template.html").read() if (BASE_DIR / "template.html").exists() else "<p>{{ data }}</p>"

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>{title}</title>
  <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Unbounded:wght@400;700;900&display=swap" rel="stylesheet">
  <style>
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    :root{--bg:#060809;--panel:#0a0d10;--card:#0e1419;--border:#1a2535;
          --amber:#f5a623;--green:#00ff88;--red:#ff4444;--text:#cdd6e0;--dim:#4a6070;--mid:#7a9ab0;
          --mono:'Space Mono',monospace;--display:'Unbounded',sans-serif;}
    body{background:var(--bg);color:var(--text);font-family:var(--mono);font-size:13px;min-height:100vh}
    header{display:flex;align-items:center;gap:16px;padding:0 32px;height:52px;
            background:var(--panel);border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100}
    .logo{font-family:var(--display);font-size:11px;font-weight:900;letter-spacing:.3em}
    .logo span{color:var(--amber)}
    main{max-width:1200px;margin:0 auto;padding:40px 32px}
    .hero{margin-bottom:40px}
    .hero-tag{font-size:10px;letter-spacing:.4em;color:var(--amber);margin-bottom:8px}
    h1{font-family:var(--display);font-size:clamp(28px,4vw,52px);font-weight:900;line-height:1}
    h1 em{font-style:normal;-webkit-text-stroke:2px {accent};color:transparent}
    .refresh-btn{margin-left:auto;background:var(--amber);color:#000;font-family:var(--mono);
                  font-size:10px;font-weight:700;letter-spacing:.15em;padding:8px 16px;
                  border:none;border-radius:2px;cursor:pointer}
    .refresh-btn:hover{background:#ffc040}
    .gen-section{background:var(--card);border:1px solid var(--border);
                  border-left:3px solid {accent};padding:20px;border-radius:2px;margin-bottom:16px}
    .gen-section-label{font-size:9px;letter-spacing:.3em;color:var(--amber);margin-bottom:12px;font-weight:700}
    .gen-table{width:100%;border-collapse:collapse;font-size:11px}
    .gen-table th{text-align:left;padding:6px 8px;border-bottom:1px solid var(--border);
                   color:var(--dim);font-size:9px;letter-spacing:.15em}
    .gen-table td{padding:6px 8px;border-bottom:1px solid rgba(26,37,53,.5);color:var(--text)}
    .gen-table-wrap{overflow-x:auto}
    .gen-stats-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:12px}
    .gen-stat{background:var(--panel);border:1px solid var(--border);padding:12px;border-radius:2px}
    .gen-stat-label{font-size:9px;letter-spacing:.15em;color:var(--dim);margin-bottom:4px}
    .gen-stat-val{font-size:18px;font-weight:700;color:var(--text)}
    .gen-raw{font-size:11px;color:var(--mid);line-height:1.6;
              background:var(--panel);padding:12px;border-radius:2px;white-space:pre-wrap;word-break:break-all}
    .gen-log{font-size:11px;line-height:1.8;max-height:300px;overflow-y:auto}
    .gen-log-line{padding:2px 0;border-bottom:1px solid rgba(26,37,53,.3);color:var(--mid)}
    .gen-error{color:var(--red);font-size:11px;padding:12px;background:rgba(255,68,68,.05);
                border:1px solid rgba(255,68,68,.2);border-radius:2px;margin-bottom:12px}
    .gen-empty{color:var(--dim);font-size:12px;text-align:center;padding:40px}
    .loading{color:var(--mid);font-size:12px;text-align:center;padding:40px}
    .data-area{min-height:200px}
  </style>
</head>
<body>
<header>
  <div class="logo"><span>[</span>{title}<span>]</span></div>
  <button class="refresh-btn" onclick="loadData()">↺ REFRESH</button>
</header>
<main>
  <div class="hero">
    <div class="hero-tag">// KUBERNETES</div>
    <h1>{icon} <em>KUBERNETES</em></h1>
  </div>
  <div class="data-area" id="dataArea"><div class="loading">Loading data...</div></div>
</main>
<script>
const BASE = "{proxy_base}";
async function loadData() {
  const area = document.getElementById('dataArea');
  area.innerHTML = '<div class="loading">Fetching data...</div>';
  try {
    const r = await fetch(BASE + '/api/data');
    const d = await r.json();
    if (d.html) { area.innerHTML = d.html; }
    else { area.innerHTML = '<div class="gen-error">No data returned</div>'; }
  } catch(e) {
    area.innerHTML = '<div class="gen-error">Error: ' + e.message + '</div>';
  }
}
loadData();
</script>
</body>
</html>"""

@app.route("/")
def index():
    html = PAGE.replace("{title}", PLUGIN_META.get("label", "Kubernetes")) \
               .replace("{icon}", PLUGIN_META.get("icon", "☸️")) \
               .replace("{accent}", PLUGIN_META.get("color", "#326ce5")) \
               .replace("{proxy_base}", PROXY_BASE)
    return html


@app.route("/api/data")
def api_data():
    try:
        data = get_data()
        rendered = render_template_string(TEMPLATE, data=data)
        return jsonify({"html": rendered, "raw": data})
    except Exception as e:
        return jsonify({"html": f'<div class="gen-error">{e}</div>', "error": str(e)})


@app.route("/api/raw")
def api_raw():
    try:
        return jsonify(get_data())
    except Exception as e:
        return jsonify({"error": str(e)})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 9200))
    print(f"[Kubernetes] Starting on http://localhost:{port}", flush=True)
    app.run(host="0.0.0.0", port=port, debug=False)
