"""
Kubernetes Plugin
Auto-generated by DevOps Suite Module Generator
Package: kubernetes
Generated: 2026-02-21 13:20

Selected features: Connect Head Namespaced Service Proxy With Path, Connect Head Namespaced Service Proxy
"""

PLUGIN_META = {
    "label": "Kubernetes",
    "icon": "☸️",
    "description": "Manage pods, deployments, services, namespaces and cluster resources",
    "order": 10,
    "color": "#326ce5",
    "package": "kubernetes",
    "generated": True,
}


def get_data():
    """Fetch data from kubernetes for all selected features."""
    try:
        import kubernetes
    except ImportError:
        return {"error": "kubernetes not installed. Run: pip install kubernetes"}

    data = {}
    
        # Connect Head Namespaced Service Proxy With Path — CoreV1Api.connect_head_namespaced_service_proxy_with_path()
        try:
            raw = CoreV1Api.connect_head_namespaced_service_proxy_with_path()
            if hasattr(raw, 'to_dict'):
                data['CoreV1Api_connect_head_namespaced_service_proxy_with_path'] = raw.to_dict()
            elif hasattr(raw, '__iter__') and not isinstance(raw, (str, bytes)):
                data['CoreV1Api_connect_head_namespaced_service_proxy_with_path'] = [item.to_dict() if hasattr(item, 'to_dict') else str(item) for item in raw]
            else:
                data['CoreV1Api_connect_head_namespaced_service_proxy_with_path'] = str(raw)
        except Exception as e:
            data['CoreV1Api_connect_head_namespaced_service_proxy_with_path_error'] = str(e)

        # Connect Head Namespaced Service Proxy — CoreV1Api.connect_head_namespaced_service_proxy()
        try:
            raw = CoreV1Api.connect_head_namespaced_service_proxy()
            if hasattr(raw, 'to_dict'):
                data['CoreV1Api_connect_head_namespaced_service_proxy'] = raw.to_dict()
            elif hasattr(raw, '__iter__') and not isinstance(raw, (str, bytes)):
                data['CoreV1Api_connect_head_namespaced_service_proxy'] = [item.to_dict() if hasattr(item, 'to_dict') else str(item) for item in raw]
            else:
                data['CoreV1Api_connect_head_namespaced_service_proxy'] = str(raw)
        except Exception as e:
            data['CoreV1Api_connect_head_namespaced_service_proxy_error'] = str(e)
    return data
